services:
    web:
        image: ritatrcr/friendlyhello  # Usamos la imagen subida a Docker Hub
        ports:
            - "4000:80"
    redis:
        image: redis
        ports:
            - "6379:6379"
        volumes:
            - "./data:/data"
        command: redis-server --appendonly yes
